# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  
  config.vm.define "pipelines" do |pipelines|
    pipelines.vm.box="deco9007/centos"
    pipelines.vm.hostname = "pipelines.do1.exam"
    pipelines.vm.provider :virtualbox do |vb|
        vb.name = "EXAM_PIP"
        vb.gui = false
        vb.memory = 2048
        vb.cpus = 1
    end
    pipelines.vm.network "private_network", ip: "192.168.56.201"
    pipelines.vm.network "forwarded_port", guest: 8080, host: 8080
    pipelines.vm.synced_folder "shared_pipelines", "/shared_jenkins"
    pipelines.vm.provision "shell", path: "add_hosts.sh"
    pipelines.vm.provision "shell", path: "addons_centos.sh"
    pipelines.vm.provision "shell", path: "centos_firewall_setup.sh"
    pipelines.vm.provision "shell", path: "pipelines/jenkins_open_ports.sh"
    pipelines.vm.provision "shell", path: "pipelines/jenkins-setup.sh"
    pipelines.vm.provision "shell", path: "install_node_exporter.sh"
  end
  
  config.vm.define "containers" do |containers|
    containers.vm.box="deco9007/centos"
    containers.vm.hostname = "containers.do1.exam"
    containers.vm.provider :virtualbox do |vb|
        vb.name = "EXAM_CO"
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 2
    end
    containers.vm.network "private_network", ip: "192.168.56.202"
    containers.vm.network "forwarded_port", guest: 80, host: 80
    containers.vm.network "forwarded_port", guest: 8080, host: 8081
    containers.vm.synced_folder "shared_gitea", "/gitea"
    containers.vm.provision "shell", path: "add_hosts.sh"
    containers.vm.provision "shell", path: "addons_centos.sh"
    containers.vm.provision "shell", path: "centos_firewall_setup.sh"
    containers.vm.provision "shell", path: "containers/do_open_ports.sh"
    containers.vm.provision "shell", path: "docker-setup_centos.sh"
    containers.vm.provision "shell", path: "containers/add_user_do.sh"
    containers.vm.provision "shell", path: "containers/install_gitea.sh"
    containers.vm.provision "shell", path: "containers/cp_utils.sh"
    containers.vm.provision "shell", path: "install_node_exporter.sh"
  end
  
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box="deco9007/centos"
    monitoring.vm.hostname = "monitoring.do1.exam"
    monitoring.vm.provider :virtualbox do |vb|
        vb.name = "EXAM_MO"
        vb.gui = false
        vb.memory = 2048
        vb.cpus = 1
    end
    monitoring.vm.network "private_network", ip: "192.168.56.203"
    monitoring.vm.network "forwarded_port", guest: 8080, host: 8082
    monitoring.vm.synced_folder "shared_prom", "/home/vagrant/prom"
    monitoring.vm.provision "shell", path: "add_hosts.sh"
    monitoring.vm.provision "shell", path: "addons_centos.sh"
    monitoring.vm.provision "shell", path: "centos_firewall_setup.sh"
    monitoring.vm.provision "shell", path: "promgraf/promgraf_open_ports.sh"
    monitoring.vm.provision "shell", path: "docker-setup_centos.sh"
    monitoring.vm.provision "shell", path: "promgraf/deploy_stack.sh"
  end

end
