global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'goprom_app'
    static_configs:
    - targets: ['192.168.56.11:8081', '192.168.56.11:8082']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: 
      - 192.168.56.11:9323
  
rule_files:
  - rules.yml
 
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - centos:9093
