global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'ne-vm203'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'ne-vm201'
    static_configs:
    - targets: ['192.168.56.201:9100']

  - job_name: 'ne-vm202'
    static_configs:
    - targets: ['192.168.56.202:9100']

  - job_name: 'cadvisor-docker'
    scrape_interval: 5s
    static_configs:
    - targets: 
      - 192.168.56.203:9323
  
rule_files:
  - rules.yml
 
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - centos:9093
