version: "3.8"
services:
    grafana:
        image: grafana/grafana-oss
        ports:
            - 3000:3000
        volumes:
            - "grafana:/var/lib/grafana"
        networks:
            - grafana-network
        restart: always
        
networks:
    grafana-network: 
