groups:
  - name: MonitorAllInstances
    rules:
      - alert: InstanceIsDown
        expr: up == 0
        for: 1m
        annotations:
          title: 'Instance {{ $labels.instance }} is down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
        labels:
          severity: 'critical'
