# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box="deco9007/centos"
    jenkins.vm.hostname = "vm11.do1.exam"
    jenkins.vm.provider :virtualbox do |vb|
        vb.name = "JE_CENTOS"
        vb.gui = false
        vb.memory = 2048
        vb.cpus = 1
    end
    jenkins.vm.network "private_network", ip: "192.168.56.11"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.synced_folder "shared_jenkins", "/shared_jenkins"
    jenkins.vm.provision "shell", path: "add_hosts.sh"
    jenkins.vm.provision "shell", path: "addons_centos.sh"
    jenkins.vm.provision "shell", path: "centos_firewall_setup.sh"
    jenkins.vm.provision "shell", path: "jenkins/jenkins_open_ports.sh"
    jenkins.vm.provision "shell", path: "jenkins/jenkins-setup.sh"
    jenkins.vm.provision "shell", path: "install_node_exporter.sh"
  end
  
  config.vm.define "docker" do |docker|
    docker.vm.box="deco9007/centos"
    docker.vm.hostname = "vm12.do1.exam"
    docker.vm.provider :virtualbox do |vb|
        vb.name = "DO_CENTOS"
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 2
    end
    docker.vm.network "private_network", ip: "192.168.56.12"
    docker.vm.network "forwarded_port", guest: 8080, host: 8081
    docker.vm.synced_folder "shared_gitea", "/gitea"
    docker.vm.provision "shell", path: "add_hosts.sh"
    docker.vm.provision "shell", path: "addons_centos.sh"
    docker.vm.provision "shell", path: "centos_firewall_setup.sh"
    docker.vm.provision "shell", path: "docker/do_open_ports.sh"
    docker.vm.provision "shell", path: "docker-setup_centos.sh"
    docker.vm.provision "shell", path: "docker/add_user_do.sh"
    docker.vm.provision "shell", path: "docker/install_gitea.sh"
    docker.vm.provision "shell", path: "docker/cp_utils.sh"
    docker.vm.provision "shell", path: "install_node_exporter.sh"
  end
  
  config.vm.define "promgraf" do |promgraf|
    promgraf.vm.box="deco9007/centos"
    promgraf.vm.hostname = "vm13.do1.exam"
    promgraf.vm.provider :virtualbox do |vb|
        vb.name = "MO_CENTOS"
        vb.gui = false
        vb.memory = 3072
        vb.cpus = 1
    end
    promgraf.vm.network "private_network", ip: "192.168.56.13"
    promgraf.vm.network "forwarded_port", guest: 8080, host: 8082
    promgraf.vm.synced_folder "shared_prom", "/home/vagrant/prom"
    promgraf.vm.provision "shell", path: "add_hosts.sh"
    promgraf.vm.provision "shell", path: "addons_centos.sh"
    promgraf.vm.provision "shell", path: "centos_firewall_setup.sh"
    promgraf.vm.provision "shell", path: "promgraf/promgraf_open_ports.sh"
    promgraf.vm.provision "shell", path: "docker-setup_centos.sh"
    promgraf.vm.provision "shell", path: "promgraf/deploy_stack.sh"
  end

end
